# Generated by Django 3.0.8 on 2020-07-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataPoint',
            new_name='Measurement',
        ),
    ]
