# Generated by Django 3.0.8 on 2020-07-17 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_auto_20200717_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gas_reading',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='latitude',
            field=models.FloatField(default=-361),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='longitude',
            field=models.FloatField(default=-361),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.IntegerField(default=-1),
        ),
    ]
