# Generated by Django 3.0.8 on 2020-07-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='gas_reading',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='2020-07-25 21:51:18.312731+00:00', max_length=200),
        ),
    ]
