# Generated by Django 3.0.8 on 2020-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20200725_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='count',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='2020-07-26 08:05:19.562616+00:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.IntegerField(),
        ),
    ]
