# Generated by Django 3.0.8 on 2020-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_auto_20200726_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='2020-07-26 17:04:42.769587+00:00', max_length=200),
        ),
    ]
