# Generated by Django 3.0.8 on 2020-08-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0009_auto_20200801_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='gas_reading',
            new_name='gas_high',
        ),
        migrations.AddField(
            model_name='measurement',
            name='gas_avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='2020-08-01 01:12:57.717217+00:00', max_length=200),
        ),
    ]
